### ISSUE TITLE
Drag scrolling not working on Firefox

### ISSUE THREAD

**Issue by zootia** [kamilkp/angular-sortable-view#21]
When you have to drag an element beyond the limits of the page or container, the list of elements should scroll when you hold the dragged item at the top or bottom of the list. They do not do so on FIrefox or IE11. Thought it was an implementation issue on my project but it seems the official demos on http://kamilkp.github.io/angular-sortable-view/#?tab=1 exhibit the same behavior.

Chrome and Safari don't have problems, only in the 2 browsers mentioned above.

**Comment by streamer** [comment]
same problem

**Comment by brainsqueezer** [comment]
This is important

**Comment by kamilkp** [comment]
Well, looks like w bug in those browsers actually. I thought the problem might be that i place the draggable element  directly in the `body` element and not the scrollable container. But it in fact is placed in the scrollable container as it should be. Note that on IE and FF you can still use the mousewheel when you drag.
