### ISSUE TITLE
sv-handle doesn't seem to be working

### ISSUE THREAD

**Issue by sonicblis** [kamilkp/angular-sortable-view#26]
Awesome library, thank you so much for the effort you're putting into it.

When adding the sv-handle to an element within an sv-element, the following error is thrown:

TypeError: undefined is not a function
    at module.directive.link (http://noteable.com/js/libs/angularSortableRepeat.js:490:30)

which is `$ctrl.handle = $element.add($ctrl.handle); // support multiple handles`

I thought it was my implementation, but it appears the [online handle demo](http://kamilkp.github.io/angular-sortable-view/#?tab=3) isn't working either (with the same error).  This is in chrome 40.0.2214.91 with angular 1.2.1.

I'm going to keep digging in and will issue a pull request if I can figure it out, but I'm not hopeful.  =]

**Comment by sonicblis** [comment]
Actually, I figured it out I think.  I'll fork and submit a pull request if you want, but really, I just changed `$element.add` to `$element.append` and my code worked.

**Comment by kamilkp** [comment]
Fixed in v0.0.13
