### ISSUE TITLE
Cloning from one list to another

### ISSUE THREAD

**Issue by PeteButler** [kamilkp/angular-sortable-view#28]
Hi, I've just found your great looking component, and am interested in using it within a current project that I am working on, however I do have a question regarding functionality I require.

Basically, I have a palette of components, and a container onto which I would like to be able to drag multiple copies of each component then reorder them. Is this type of functionality currently available in your component (at present I am using ui-sortable with cloning but would rather use your library if possible aas it would make for a much cleaner solution)

**Comment by Blaze34** [comment]
Very old question, but no answers yet.
PeteButler, How you solve your problem?

**Comment by PeteButler** [comment]
By switching to another component https://github.com/a5hik/ng-sortable

**Comment by roman-yerin** [comment]
+1 for this feature

**Comment by roman-yerin** [comment]
Here is my patch https://github.com/kamilkp/angular-sortable-view/pull/78 if somebody is still interested in it
