### ISSUE TITLE
Nested Draggables

### ISSUE THREAD

**Issue by dmackerman** [kamilkp/angular-sortable-view#35]
Howdy! Thanks for the awesome library. 

We're trying to build a "kanban" board of sorts that allows you to drag items between columns (got this working), but also re-arrange the columns themselves. Here's a quick example of our data structure. 

``` js
this.journey = [{
    stageId: 0,
    name: 'First 30 Days',
    tasks: [{
        ord: 0,
        taskId: 3995,
        name: 'thecium unimpregnable speciology Sphaerostilbe bonneted tamandua salicylyl baggie splanchnic'
    }, {
        ord: 1,
        taskId: 8595,
        name: 'undermate politics noncorroborative dolomitize sesquicentennial governably praseolite Uigurian onofrite'
    }, {
        ord: 2,
        taskId: 4495,
        name: 'Hillhousia bicycloheptane trog snuggery dissimulative evisceration Koellia departition extracosmic'
    }]
} {
    ...
}]
```

We have a container div in which we placed `sv-root`, and we `ngRepeat` over the "stages" and display their tasks. We use `sv-part` like so:

``` html
ng-repeat="stage in journey.journey" sv-part="journey.journey[$index].tasks"
```

And use `sv-element` on the individual tasks. This all works great. However, when we try to apply another `sv-element` to the columns, the system kinda breaks down. Essentially we can drag columns into columns, and the drag events for tasks no longer work. Any ideas on how to solve this with your library?

Think I might need another `sv-root` with an attribute, but not sure how to structure that.

**Comment by dmackerman** [comment]
So, I kinda answered my own question and figured it out! :+1: 

Only issue I'm seeing now is that I'm no longer seeing my `sv-placeholders` appear. The "space" for the tasks item to drop appears but the placeholder doesn't. The placeholder for columns doesn't appear at all.

**Comment by kamilkp** [comment]
You're gonna have to create a sample fiddle for me. Without it it is hard to tell what's going on that causes the problem.

**Comment by dmackerman** [comment]
Yeah, I'll try and throw one together. The gist is when you have nested lists, only one `sv-placeholder` shows up - the one that's defined first.

**Comment by mcodev1** [comment]
@dmackerman Can you provide code examples of how you solved this problem? It would help myself or anyone else stumbling across this issue in need of a similar or identical solution.

**Comment by hauthorn** [comment]
I am also interested in seeing how you solved the problem with nested draggables.

**Comment by dmackerman** [comment]
This is how we solved it. I tried to remove all the non-relevant parts. Note the important part is the `sv-part="user_flow.user_flow.stages[$index].tasks"`

```html
<md-content sv-root="columns" sv-part="user_flow.user_flow.stages" sv-on-sort="user_flow.onColumnSort($item, $partFrom, $partTo, $indexFrom, $indexTo)" flex>
    <div sv-placeholder class="ps-journey-column-placeholder" flex></div>
    <div class="ps-journey-col" ng-repeat="stage in user_flow.user_flow.stages | orderBy: 'position'" sv-element>
        <div class="ps-journey-col-header">
            <span sv-handle><i class="ps-journey-col-drag ion-drag"></i></span>
            {{ stage.name }}
        </div>
        <div class="ps-journey-col-content" sv-root="tasks" sv-part="user_flow.user_flow.stages[$index].tasks" sv-on-sort="user_flow.onTaskSort($item, $partFrom, $partTo, $indexFrom, $indexTo, stage)">
                <span sv-element class="ps-task-name" style="font-size:14px">{{ task.name }}</span>
            </div>
        </div>
    </div>
</md-content>
```
