### ISSUE TITLE
svOnStart errors.

### ISSUE THREAD

**Issue by dmackerman** [kamilkp/angular-sortable-view#38]
Angular doesn't like binding DOM nodes to expressions.
https://docs.angularjs.org/error/$parse/isecdom?p0=journey.onTaskDrag($item,%20$part,%20$index,%20$helper

**Comment by kamilkp** [comment]
Isn't it a duplicate of #12 ?

**Comment by dmackerman** [comment]
Ah, yes. Sorry!

Another question - would there be a way to access the `$helper` inside a directive instead? I want to add and remove classes, but doing so in a controller feels wrong.

**Comment by lookfirst** [comment]
Ugh... @kamilkp when will you fix this?
