### ISSUE TITLE
Can't find javascript documentation, only html code

### ISSUE THREAD

**Issue by andrieski** [kamilkp/angular-sortable-view#41]
Hi, although the module is pretty self explanatory and I got it working, I noticed that for the examples, you only provide the html code. Where is the angular code (initiating the scope object, for one)? I've tried a couple of these draggable modules and there are options (like cancelling drags) that need to be coded in angular, but I haven't been able to find any examples of that so far if your documentation. 

Thanks!

**Comment by kamilkp** [comment]
Because it doesn't require any javascript code at all. Nor any other dependencies. Pull the gh-pages branch and see for yourself.

**Comment by andrieski** [comment]
Oh ok, that makes sense, thanks!
