### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by taylor1791** [kamilkp/angular-sortable-view#42]
Is there any hesitation to publish an npm package?

**Comment by kamilkp** [comment]
No problem. But would you like to use the lib with webpack?

**Comment by taylor1791** [comment]
I am not using webpack at this point in time. I could probably be convinced to use webpack, but it would not be an immediate transition.

**Comment by alexandernst** [comment]
+1 to this.  You already have the `package.json` file. You just need to `npm publish` it :)

**Comment by kamilkp** [comment]
Done
