### ISSUE TITLE
Remove window constraints for draggable elements?

### ISSUE THREAD

**Issue by andrieski** [kamilkp/angular-sortable-view#43]
Is there any way to remove the window constraints? For example, If I'm moving a large element, the window borders make it awkward to move the element, especially if there are smaller elements nearby. I guess a related question is if it's possible to lower the opacity of the element as its being dragged? 

What I'm doing is laying out large containers side to side with draggable blocks inside. I'm going horizontally, and adding containers and blocks. I don't know if this is expected or normal behavior,but  the element won't move past a certain point, even if there's other containers and blocks outside the range. This may have to do with the window constraints, but I'm not sure. Any suggestions?

I was able to replicate the issue with the jsbin you created to demonstrate nested draggables over [here](http://jsbin.com/qujuyuhubi/1/edit) by adding flexbox like this:

```js
<div ng-app="app">
    <div sv-root>
      <div style="display:flex; flex-direction: row" sv-part="items" >
        <div style="width: 200px; min-width: 200px" ng-repeat="item in items" sv-element>
          <div sv-handle>{{item}}</div>
          <div sv-root>
            <div sv-part="item.items">
              <div sv-element ng-repeat="inner in item.items">
                {{inner}}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>  
  </div>
```

**Comment by Pecka40** [comment]
As I understood your question you have to use this: sv-element="{containment:html}"
I just found out this option too. :D Didnt see any documentation about "options", only that sv-element can have them. So I went throught the source and found out about it.

**Comment by andrieski** [comment]
Ah yes, you're totally right! Btw, are "options" the only thing he didn't mention in the documentation or are there other hidden gems like this?

**Comment by Pecka40** [comment]
I have no idea to be honest.
