### ISSUE TITLE
sv-on-start seems to run too late and need callback for when sorting is done even if order didn't change

### ISSUE THREAD

**Issue by dnchristiansen** [kamilkp/angular-sortable-view#6]
I should probably log two separate issues, but both are related to what I'm trying to accomplish, so I wanted to put all the info into one issue. I have a series of sections with a header and a body that I want to be able to drag and drop around. Because the body can be a bit big, I want to hide all the bodies while dragging, and then show them again after the dragging is done.

First, to hide them when dragging starts, I used sv-on-start. However, it doesn't seem to run the expression until I've stopped dragging. See this fiddle: http://jsfiddle.net/ttm849ef/
The bodies don't collapse until after the dragging stops.

I got around this using ng-mousedown. See this fiddle: http://jsfiddle.net/rLsvuk1r/
However, I'd rather use sv-on-sort as this is what it was made for (unless I'm misunderstanding something).

Secondly, I need a callback for when the dragging stops. sv-on-sort works great when the actual order changes, but if a user decides to not change the order after beginning to drag, I need a callback that will fire in this case. See this fiddle: http://jsfiddle.net/5xsr13ow/
If I move the section to a new spot, everything works like I want. However, if I leave it in the same place, the sv-on-sort doesn't fire, and everything remains hidden. I understand why a sv-on-sort callback wouldn't fire in this case, but I'm hoping for some kind of callback that can be called even if the order didn't change.

**Comment by sibasisj** [comment]
Hi kamilkp,

I am pretty much new to angular js. 
While dragging in upward direction, the scroll function is not working. Is there any way to do it. 
Thanks in advance.
