### ISSUE TITLE
Any chance of seeing a new release soon?

### ISSUE THREAD

**Issue by eugenious** [kamilkp/angular-sortable-view#77]
Of all the angular drag-and-drop sorting I've tried, this one works the best. But it appears that there are many issues and pull requests in flight.

Has this project been abandoned? The last update was many moons ago.

**Comment by roman-yerin** [comment]
It looks like the author is not interested in it anymore. One more dead project on Github

**Comment by kamilkp** [comment]
Merges some PRs and released.

**Comment by eugenious** [comment]
Thanks Kamil for listening. It's not easy to maintain open source projects, so thank you for making this project and maintaining it.
