### ISSUE TITLE
Uncaught TypeError: closestElement.call(...).getBoundingClientRect is not a function(…)

### ISSUE THREAD

**Issue by haslamc** [kamilkp/angular-sortable-view#79]
When I try and run the most basic example in 0.0.14, I get the following error (in Chrome dev tools)
:
Uncaught TypeError: closestElement.call(...).getBoundingClientRect is not a function(…)
onMousedown	@	angular-sortable-view.js:408

which seems related to this fix added in:

https://github.com/kamilkp/angular-sortable-view/commit/8639eac04594401dee6536442484019999f31bc6

Am I doing something wrong?

**Comment by richardsawyer** [comment]
Yep. The update in 0.0.14 breaks it for me too. Reverted to 0.0.13 and all good.

**Comment by kamilkp** [comment]
Reverted that "fix". Please download version 0.0.15.

**Comment by pichotweb** [comment]
I'm using the version 0.0.15 and still get this error.

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

**Comment by jamez14** [comment]
I got this error as well and it was because of improper namespacing. The `closestElement` variable was colliding with another library I have installed (angular ui-select) so it was using that library's implementation of `closestElement` instead of angular-sortable-view's implementation.

**Comment by SergeyKatugin** [comment]
Still have a problem

**Comment by gregoryalary** [comment]
Still have the problem too.
