### ISSUE TITLE
nested sorting

### ISSUE THREAD

**Issue by jekamoroz** [kamilkp/angular-sortable-view#8]
thank you very much for plugin
and what about nested sorting?

**Comment by captaincoo1** [comment]
I am looking for this functionality too.

**Comment by kamilkp** [comment]
Have you tried [ng-nestable](https://github.com/kamilkp/ng-nestable) ?

**Comment by captaincoo1** [comment]
I haven't yet. I need parents to be sortable and children to be sortable in the parents, but parents should stay as parents and not be able to be children.  Is this possible with ng-nestable?

**Comment by captaincoo1** [comment]
I tried to set up parents and children being both independently sortable with angular-sortable-view, but only the parent can be  dragged. I tried to limit the click and drag area of the parent using 'sv-handle' but that didn't do anything.

**Comment by kamilkp** [comment]
well, angular-sortable-view should be able to handle that scenario. i'll try to use it like that myself, and see if i run into similar problems

**Comment by kamilkp** [comment]
Using 'sv-handles' does the trick. **but** you're most likely experiencing the #18. See [this](http://jsbin.com/modusehoti/1/edit) jsbin to see it working. I will be pushing a new version in a few moments that will have this fixed

**Comment by kamilkp** [comment]
Works in v0.0.13

**Comment by captaincoo1** [comment]
Wow, thank you so much for getting this work!  I've got my project now working too.  It'd be great if I could drag children to other parents too, but I'm happy with this for now!

**Comment by kamilkp** [comment]
If you want to be able to move children between parents just set a common value of the inner elements' sv-root attribute. That will group them together.

**Comment by captaincoo1** [comment]
Thanks! It's totally working now.
