### ISSUE TITLE
Dragging items containing images is buggy

### ISSUE THREAD

**Issue by DrDanRyan** [kamilkp/angular-sortable-view#90]
The majority of the time (but not always, I can't see a pattern, maybe 70/30 random) when dragging an item containing an image, I have to release the mouse button to get the item to start moving and then click the mouse button again to drop the item.

I think it has to do with whether my browser thinks I am trying to drag the image (like to save it to my desktop) or whether ng-sortable-view handles the click instead.

I am using an up-to-date version of Chrome.

**Comment by DrDanRyan** [comment]
I just figured out that the difference is based on where in the sv-element I click. If I click in the top half of the element, ng-sortable-view works normally.  If I initiate the drag by clicking in the bottom half of the element (even below the picture) my browser tries to drag the picture until I release the mouse button, at which time ng-sortable-view takes over and I can drag it around and drop it by clicking a second time.

**Comment by thelarz** [comment]
I had the same problem, if you'll just add draggable="false" to the img element, it will be fixed!

**Comment by DrDanRyan** [comment]
Old and irrelevant
