### ISSUE TITLE
It won't work with default "$ctrl" in component view

### ISSUE THREAD

**Issue by srokatonie** [kamilkp/angular-sortable-view#96]
I was not declaring `controllerAs` in my component and using default `$ctrl` in template. `sv-root` would be just empty div.

After couple of hours I discovered that you have to use `controllerAs: 'something'` and use it in your template in order to have this directive working.

Hope that helps someone.

**Comment by vlio20** [comment]
@srokatonie, did you use 1.5 component in your case?

**Comment by srokatonie** [comment]
@vlio20 Yes, Angular 1.5.7

**Comment by wuzhitian** [comment]
Thanks a lot! It works! :)

**Comment by alirezamirian** [comment]
Being forced to use `controllerAs: "somethingOtherThan$ctrl"` is obviously not a good idea. I think `sv-part` directive should use an isolated scope. to prevent scope collision.

**Comment by vlio20** [comment]
@srokatonie, why did you close it?

**Comment by knigal** [comment]
why close??

**Comment by alejandroiglesias** [comment]
Stumbled again upon this 😞
